name: Monkalytics

services:
  postgres:
    image: postgres:18-alpine
    container_name: monkalytics-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monkalytics-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monkalytics-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - monkalytics-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: monkalytics-frontend
  #   environment:
  #     VITE_API_URL: http://localhost:8080
  #     VITE_WS_URL: ws://localhost:8080
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - monkalytics-network

networks:
  monkalytics-network:
    driver: bridge

volumes:
  postgres_data:
