name: Monkalytics

services:
  postgres:
    image: postgres:18-alpine
    container_name: monkalytics-postgres
    environment:
      POSTGRES_DB: monkalytics-db
      POSTGRES_USER: monka
      POSTGRES_PASSWORD: monkalytics123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monka"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monkalytics-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: monkalytics-backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://monka:monkalytics123@postgres:5432/monkalytics-db
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://frontend:5173
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monkalytics-network
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--quiet",
    #       "--tries=1",
    #       "--spider",
    #       "http://localhost:8080/actuator/health",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: monkalytics-frontend
  #   environment:
  #     VITE_API_URL: http://localhost:8080
  #     VITE_WS_URL: ws://localhost:8080
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - monkalytics-network

networks:
  monkalytics-network:
    driver: bridge

volumes:
  postgres_data:
